### ISSUE TITLE
RFC. Comparative review feedback, and feature requests.

### ISSUE THREAD

**Issue by marblewraith** [usernamehw/vscode-find-jump#29]
Hi 👋

I'm looking into creating my own extension pack. Because of this i've been reviewing vim-easymotion / aceJump extensions in the VScode marketplace.

### My experience with extensions of this type

<details>
<summary>WARNING: WOT incoming!</summary>

1. [Jumpy](https://marketplace.visualstudio.com/items?itemName=wmaurer.vscode-jumpy) - For what it does, it works well. But it lacks features for selecting text, and the jump characters aren't customizable in terms of font, colors, etc.

2. [Meta Jump](https://marketplace.visualstudio.com/items?itemName=metaseed.MetaJump) - Is probably the most full featured. But the default configuration is insanely *bad*, it lacks a "dim mode", sometimes it would generate jumps that were +3 characters long (for no reason), and I had stability issues when using it (maybe because it was designed for use with Vim or as a dependency of MetaGo? Not sure).

3. [Code Ace Jumper](https://marketplace.visualstudio.com/items?itemName=lucax88x.codeacejumper) - The oldest (going by repo age) and still functional. But it is not very actively maintained, the "dim mode" doesn't work as expected, and the settings API has several options in there that don't actually do anything (have been deprecated but not removed).

... And now we come to 4. [Find => Jump](https://marketplace.visualstudio.com/items?itemName=usernamehw.find-jump)

In my opinion, it is **the best** out of all these listed here 💯

It provides equal or better functionality as Code Ace Jumper, without any of the shortcomings, no issues with configuration and (more importantly) stability either. 👍

</details>

### Feature Requests

Meta Jump is the most full featured "jumper" i have used. If it worked correctly, there are 2 features it has that, as far as i know, none of the other ones have, including `find => jump`. I request these be added:

- **Smart cursor positioning. From the Meta Jump docs:**

> the Alt+/ shortcut will trigger the metaGo.gotoSmart command which intelligently set cursor position after navigation:
> - if the target is at the begin of the word, the cursor will be set before target character, otherwise after it;
> - The 'word' is defined as a group of all alphanumeric or punctuation characters.

- **Insert Multi-Cursors**

1. Activate trigger (`alt+;`)
2. type target letter -> type jump character -> insert cursor at location
3. type target letter -> type jump character -> insert second cursor at location
...
Activate trigger to exit mode (`alt+;`) while keeping cursors

Note: This mode would also need to respond to the editor action : Cursor Undo (default `ctrl+u`), in case one was added in the wrong place.

**Comment by usernamehw** [comment]
This extension is probably not the best one. There should be extensions somewhere that don't conflict with Vim (using Quick Input instead of overriding "type" command). And there should be extensions that allow to jump to any visible editor (split/grid).

Maybe https://marketplace.visualstudio.com/items?itemName=mbnuqw.jumpt or https://marketplace.visualstudio.com/items?itemName=shuworks.vscode-jump-to-hint ?

In any case - I don't have a lot of free time to work on it.

**Comment by marblewraith** [comment]
Thanks for the recommendations I'll give them a look 👍
