### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by saltsoftdrink** [usernamehw/vscode-find-jump#32]
@usernamehw its been a more than a Year When will you complete this TODO - 

https://github.com/usernamehw/vscode-find-jump?tab=readme-ov-file#todo-in-the-future

**Comment by usernamehw** [comment]
Not in the near future (1-2 years). I think there are tons of similar extensions (at least some of them should support split/grid):

- tag:AceJump https://marketplace.visualstudio.com/search?term=tag%3AAceJump&target=VSCode&category=All%20categories&sortBy=Relevance
- tag:jumpy https://marketplace.visualstudio.com/search?term=tag%3Ajumpy&target=VSCode&category=All%20categories&sortBy=Relevance
- tag:jump https://marketplace.visualstudio.com/search?term=tag%3Ajump&target=VSCode&category=All%20categories&sortBy=Relevance

**Comment by saltsoftdrink** [comment]
> Not in the near future (1-2 years). I think there are tons of similar extensions (at least some of them should support split/grid):
> 
> * tag:AceJump https://marketplace.visualstudio.com/search?term=tag%3AAceJump&target=VSCode&category=All%20categories&sortBy=Relevance
> * tag:jumpy https://marketplace.visualstudio.com/search?term=tag%3Ajumpy&target=VSCode&category=All%20categories&sortBy=Relevance
> * tag:jump https://marketplace.visualstudio.com/search?term=tag%3Ajump&target=VSCode&category=All%20categories&sortBy=Relevance

Ok, Thanks for that ☺️
